/**
 * Dynamic PWA manifest helper for customer portal install.
 *
 * The static manifest in vite.config.ts has start_url='/' (admin
 * context). For customer installs, we override at runtime so the
 * installed PWA shortcut opens directly at the customer's portal
 * with their token.
 *
 * Sharp edge: if the token is rotated server-side, the installed
 * shortcut becomes a dead link until the customer re-installs from
 * a fresh Messenger link.
 */

export function setCustomerPortalManifest(token: string): void {
  if (!token) return;

  const manifest = {
    name: 'Cha Jewels',
    short_name: 'Cha Jewels',
    description: 'Cha Jewels Customer Portal',
    theme_color: '#D4AF37',
    background_color: '#000000',
    display: 'standalone',
    orientation: 'portrait',
    scope: '/',
    start_url: `/portal?token=${encodeURIComponent(token)}`,
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };

  const json = JSON.stringify(manifest);
  const dataUrl = `data:application/manifest+json;charset=utf-8,${encodeURIComponent(json)}`;

  let link = document.querySelector('link[rel="manifest"]') as HTMLLinkElement | null;
  if (!link) {
    link = document.createElement('link');
    link.rel = 'manifest';
    document.head.appendChild(link);
  }
  link.href = dataUrl;
}

export function resetToDefaultManifest(): void {
  // Restore the static admin-context manifest generated by
  // vite-plugin-pwa. Default path is /manifest.webmanifest.
  const link = document.querySelector('link[rel="manifest"]') as HTMLLinkElement | null;
  if (link) {
    link.href = '/manifest.webmanifest';
  }
}
