-- Random Copy Message lines: seed pools (owner-confirmed plan 2026-10-01 01:29 JST).
-- 25 message types, 37 pools, 6 lines each (222 lines). Line sort=1 of every pool is
-- today's exact wording, so a pool reduced to line 1 reproduces today's message.
-- Idempotent: a pool is only inserted when that (message_type, part) has no rows yet.
-- Placeholders filled by code: {name} {first_name} {invoice} {due_date} {days_ago} {link}.
BEGIN;
INSERT INTO public.message_lines (message_type, part, body, active, sort)
SELECT v.message_type, v.part, v.body, true, v.sort
FROM (VALUES
  ('payment_received', 'opening', E'Thank you for your payment.', 1),
  ('payment_received', 'opening', E'Hi {first_name}! Salamat po sa payment mo.', 2),
  ('payment_received', 'opening', E'Thank you so much, {first_name}!', 3),
  ('payment_received', 'opening', E'Hi {first_name}, maraming salamat po sa bayad mo.', 4),
  ('payment_received', 'opening', E'Hello {first_name}! Thank you po for your payment.', 5),
  ('payment_received', 'opening', E'Salamat po, {first_name}! Thank you for your payment.', 6),
  ('payment_received_multi', 'opening', E'Thank you for your payments.', 1),
  ('payment_received_multi', 'opening', E'Hi {first_name}! Salamat po sa mga payment mo.', 2),
  ('payment_received_multi', 'opening', E'Thank you so much for your payments, {first_name}!', 3),
  ('payment_received_multi', 'opening', E'Maraming salamat po, {first_name}!', 4),
  ('payment_received_multi', 'opening', E'Hello {first_name}! Thank you po for your payments.', 5),
  ('payment_received_multi', 'opening', E'Salamat po, {first_name}! Thank you for your payments.', 6),
  ('thanks_trust', 'closing', E'Thank you for your continued trust in Cha Jewels! 🧡', 1),
  ('thanks_trust', 'closing', E'Salamat po sa patuloy na tiwala sa Cha Jewels! 🧡', 2),
  ('thanks_trust', 'closing', E'Thank you for always trusting Cha Jewels! 🧡', 3),
  ('thanks_trust', 'closing', E'Maraming salamat po for your continued trust in Cha Jewels! 🧡', 4),
  ('thanks_trust', 'closing', E'We truly appreciate your trust in Cha Jewels — salamat po! 🧡', 5),
  ('thanks_trust', 'closing', E'Thank you for staying with Cha Jewels! Salamat po 🧡', 6),
  ('thanks_business', 'closing', E'Thank you for your continued trust in Cha Jewels. We appreciate your business! 🧡', 1),
  ('thanks_business', 'closing', E'Salamat po sa patuloy na tiwala sa Cha Jewels. We truly appreciate you! 🧡', 2),
  ('thanks_business', 'closing', E'Thank you for always choosing Cha Jewels. We appreciate your business! 🧡', 3),
  ('thanks_business', 'closing', E'Maraming salamat po for your trust in Cha Jewels. We appreciate your support! 🧡', 4),
  ('thanks_business', 'closing', E'Thank you for your continued trust in Cha Jewels — we\'re grateful for you! 🧡', 5),
  ('thanks_business', 'closing', E'We appreciate your business and your trust in Cha Jewels. Salamat po! 🧡', 6),
  ('accounts_all_completed', 'opening', E'Dear {name},\n\nAll your layaway accounts have been completed. 🎉', 1),
  ('accounts_all_completed', 'opening', E'Hi {first_name}!\n\nAll your layaway accounts are now completed. 🎉', 2),
  ('accounts_all_completed', 'opening', E'Dear {name},\n\nCongratulations po — all your layaway accounts have been completed! 🎉', 3),
  ('accounts_all_completed', 'opening', E'Hello {first_name}!\n\nGood news po: all your layaway accounts are completed. 🎉', 4),
  ('accounts_all_completed', 'opening', E'Hi {first_name},\n\nTapos na po lahat ng layaway accounts mo — all completed! 🎉', 5),
  ('accounts_all_completed', 'opening', E'Dear {first_name},\n\nAll your layaway accounts have been completed. Congratulations po! 🎉', 6),
  ('new_account_split_payment', 'opening', E'Dear {name},\n\nThank you for your payment.', 1),
  ('new_account_split_payment', 'opening', E'Hi {first_name},\n\nSalamat po sa payment mo.', 2),
  ('new_account_split_payment', 'opening', E'Dear {name},\n\nMaraming salamat po sa bayad mo.', 3),
  ('new_account_split_payment', 'opening', E'Hello {first_name}!\n\nThank you so much for your payment.', 4),
  ('new_account_split_payment', 'opening', E'Hi {first_name}!\n\nThank you po for your payment.', 5),
  ('new_account_split_payment', 'opening', E'Dear {first_name},\n\nSalamat po! Thank you for your payment.', 6),
  ('new_account_split_payment', 'closing', E'Thank you for your continued trust in Cha Jewels. We appreciate your business! 💛', 1),
  ('new_account_split_payment', 'closing', E'Salamat po sa patuloy na tiwala sa Cha Jewels. We truly appreciate you! 💛', 2),
  ('new_account_split_payment', 'closing', E'Thank you for always choosing Cha Jewels. We appreciate your business! 💛', 3),
  ('new_account_split_payment', 'closing', E'Maraming salamat po for your trust in Cha Jewels. We appreciate your support! 💛', 4),
  ('new_account_split_payment', 'closing', E'Thank you for your continued trust in Cha Jewels — we\'re grateful for you! 💛', 5),
  ('new_account_split_payment', 'closing', E'We appreciate your business and your trust in Cha Jewels. Salamat po! 💛', 6),
  ('contact_us', 'closing', E'For any questions, please contact Cha Jewels directly.', 1),
  ('contact_us', 'closing', E'If you have any questions, please contact Cha Jewels directly.', 2),
  ('contact_us', 'closing', E'For questions, please message Cha Jewels directly.', 3),
  ('contact_us', 'closing', E'Kung may tanong po kayo, please contact Cha Jewels directly.', 4),
  ('contact_us', 'closing', E'For any concerns, please reach out to Cha Jewels directly.', 5),
  ('contact_us', 'closing', E'Para sa anumang tanong, please contact Cha Jewels directly.', 6),
  ('settlement_contact', 'closing', E'For any questions, please contact Cha Jewels directly. 💛', 1),
  ('settlement_contact', 'closing', E'If you have any questions, please contact Cha Jewels directly. 💛', 2),
  ('settlement_contact', 'closing', E'For questions, please message Cha Jewels directly. 💛', 3),
  ('settlement_contact', 'closing', E'Kung may tanong po kayo, please contact Cha Jewels directly. 💛', 4),
  ('settlement_contact', 'closing', E'For any concerns, please reach out to Cha Jewels directly. 💛', 5),
  ('settlement_contact', 'closing', E'Para sa anumang tanong, please contact Cha Jewels directly. 💛', 6),
  ('extension_closing', 'closing', E'Please settle promptly to avoid permanent forfeiture. 💛', 1),
  ('extension_closing', 'closing', E'Please settle on time to avoid permanent forfeiture. 💛', 2),
  ('extension_closing', 'closing', E'Pakisettle po agad to avoid permanent forfeiture. 💛', 3),
  ('extension_closing', 'closing', E'Kindly settle promptly so your account is not permanently forfeited. 💛', 4),
  ('extension_closing', 'closing', E'Please make your payment promptly to avoid permanent forfeiture. 💛', 5),
  ('extension_closing', 'closing', E'Paki-settle po agad para maiwasan ang permanent forfeiture. 💛', 6),
  ('portal_activation', 'opening', E'Hi {name} 💛\n\nYour Cha Jewels Hub Portal has been successfully created.', 1),
  ('portal_activation', 'opening', E'Hi {first_name} 💛\n\nYour Cha Jewels Hub Portal is ready!', 2),
  ('portal_activation', 'opening', E'Hello {first_name}! 💛\n\nGood news po — your Cha Jewels Hub Portal has been created.', 3),
  ('portal_activation', 'opening', E'Hi {first_name} 💛\n\nNaka-set up na po ang Cha Jewels Hub Portal mo.', 4),
  ('portal_activation', 'opening', E'Hi {name} 💛\n\nYour Cha Jewels Hub Portal is all set up.', 5),
  ('portal_activation', 'opening', E'Hello {first_name} 💛\n\nReady na po ang Cha Jewels Hub Portal mo!', 6),
  ('portal_activation', 'closing', E'If you have any questions or need assistance, feel free to message us anytime.', 1),
  ('portal_activation', 'closing', E'May tanong po? Feel free to message us anytime.', 2),
  ('portal_activation', 'closing', E'If you need any help, just message us anytime po.', 3),
  ('portal_activation', 'closing', E'For any questions or help, message us anytime — we\'re happy to assist.', 4),
  ('portal_activation', 'closing', E'Kung may kailangan po kayo, feel free to message us anytime.', 5),
  ('portal_activation', 'closing', E'Questions or concerns? Message us anytime po, we\'re here to help.', 6),
  ('portal_link_share', 'full', E'Hi {name}! Here\'s your Cha Jewels Hub portal: {link}', 1),
  ('portal_link_share', 'full', E'Hi {first_name}! 💛 Ito po ang link ng Cha Jewels Hub portal mo: {link}', 2),
  ('portal_link_share', 'full', E'Hello {first_name}! Here\'s your Cha Jewels Hub portal link: {link}', 3),
  ('portal_link_share', 'full', E'Hi {first_name}, you can view your Cha Jewels account here po: {link}', 4),
  ('portal_link_share', 'full', E'Hello po {first_name}! Your Cha Jewels Hub portal: {link}', 5),
  ('portal_link_share', 'full', E'Hi {first_name}! Pwede nyo pong i-check ang account nyo sa Cha Jewels Hub portal: {link}', 6),
  ('portal_setup_invite', 'full', E'Hi {name}! Set up your Cha Jewels portal access here: {link}', 1),
  ('portal_setup_invite', 'full', E'Hi {first_name}! 💛 Pa-set up na po ng Cha Jewels portal access mo dito: {link}', 2),
  ('portal_setup_invite', 'full', E'Hello {first_name}! You can set up your Cha Jewels portal access here: {link}', 3),
  ('portal_setup_invite', 'full', E'Hi {first_name}, set up your Cha Jewels portal login here po: {link}', 4),
  ('portal_setup_invite', 'full', E'Hello po {first_name}! Here\'s the link to set up your Cha Jewels portal access: {link}', 5),
  ('portal_setup_invite', 'full', E'Hi {first_name}! I-set up nyo na po ang Cha Jewels portal access nyo dito: {link}', 6),
  ('reminder_upcoming', 'opening', E'Hi {name}! 👋\n\nThis is a friendly heads-up from Cha Jewels — your next layaway payment for INV #{invoice} is coming up on {due_date}.', 1),
  ('reminder_upcoming', 'opening', E'Hi {first_name}! 👋\n\nFriendly reminder po from Cha Jewels — your next layaway payment for INV #{invoice} is on {due_date}.', 2),
  ('reminder_upcoming', 'opening', E'Hello {first_name}! 👋\n\nJust a heads-up po: your next layaway payment for INV #{invoice} is coming up on {due_date}.', 3),
  ('reminder_upcoming', 'opening', E'Hi {first_name}! 👋\n\nPaalala lang po from Cha Jewels — malapit na ang next layaway payment mo for INV #{invoice} on {due_date}.', 4),
  ('reminder_upcoming', 'opening', E'Hello po {first_name}! 👋\n\nYour next layaway payment for INV #{invoice} is coming up on {due_date}. Just a friendly reminder from Cha Jewels.', 5),
  ('reminder_upcoming', 'opening', E'Hi {first_name}! 👋\n\nQuick reminder from Cha Jewels — your next layaway payment for INV #{invoice} is coming up on {due_date}.', 6),
  ('reminder_upcoming', 'closing', E'Thank you for staying on track! 💎', 1),
  ('reminder_upcoming', 'closing', E'Salamat po sa pagiging on time! 💎', 2),
  ('reminder_upcoming', 'closing', E'Thank you for keeping up with your payments! 💎', 3),
  ('reminder_upcoming', 'closing', E'Maraming salamat po! 💎', 4),
  ('reminder_upcoming', 'closing', E'Thank you po for staying on track! 💎', 5),
  ('reminder_upcoming', 'closing', E'Salamat po, and thank you for staying on track! 💎', 6),
  ('reminder_due_today', 'opening', E'Hi {name} 💎\n\nYour layaway payment for Invoice #{invoice} is due TODAY, {due_date}.', 1),
  ('reminder_due_today', 'opening', E'Hi {first_name} 💎\n\nPaalala po: your layaway payment for Invoice #{invoice} is due TODAY, {due_date}.', 2),
  ('reminder_due_today', 'opening', E'Hello {first_name} 💎\n\nJust a reminder po — your layaway payment for Invoice #{invoice} is due TODAY, {due_date}.', 3),
  ('reminder_due_today', 'opening', E'Hi {first_name} 💎\n\nTODAY po ang due ng layaway payment mo for Invoice #{invoice} ({due_date}).', 4),
  ('reminder_due_today', 'opening', E'Hi {first_name} 💎\n\nYour layaway payment for Invoice #{invoice} is due TODAY po, {due_date}.', 5),
  ('reminder_due_today', 'opening', E'Hello po {first_name} 💎\n\nReminder from Cha Jewels: your payment for Invoice #{invoice} is due TODAY, {due_date}.', 6),
  ('reminder_grace', 'opening', E'Hi {name} 💎\n\nYour layaway payment for Invoice #{invoice} was due on {due_date} ({days_ago}).', 1),
  ('reminder_grace', 'opening', E'Hi {first_name} 💎\n\nPaalala po: your layaway payment for Invoice #{invoice} was due on {due_date} ({days_ago}).', 2),
  ('reminder_grace', 'opening', E'Hello {first_name} 💎\n\nJust a reminder po — your layaway payment for Invoice #{invoice} was due on {due_date} ({days_ago}).', 3),
  ('reminder_grace', 'opening', E'Hi {first_name} 💎\n\nLumampas na po ang due date ng layaway payment mo for Invoice #{invoice} — it was due on {due_date} ({days_ago}).', 4),
  ('reminder_grace', 'opening', E'Hello po {first_name} 💎\n\nOur records show your layaway payment for Invoice #{invoice} was due on {due_date} ({days_ago}).', 5),
  ('reminder_grace', 'opening', E'Hi {first_name} 💎\n\nFriendly reminder from Cha Jewels: your payment for Invoice #{invoice} was due on {due_date} ({days_ago}).', 6),
  ('thanks_choosing', 'closing', E'Thank you for choosing Cha Jewels 💛', 1),
  ('thanks_choosing', 'closing', E'Salamat po sa pagpili sa Cha Jewels 💛', 2),
  ('thanks_choosing', 'closing', E'Thank you po for choosing Cha Jewels 💛', 3),
  ('thanks_choosing', 'closing', E'Maraming salamat po for choosing Cha Jewels 💛', 4),
  ('thanks_choosing', 'closing', E'Thank you for being with Cha Jewels 💛', 5),
  ('thanks_choosing', 'closing', E'Salamat po, and thank you for choosing Cha Jewels 💛', 6),
  ('reminder_overdue', 'opening', E'Hi {name}! 👋\n\nThis is a friendly reminder from Cha Jewels that your layaway payment for INV #{invoice} was due on {due_date} ({days_ago}).', 1),
  ('reminder_overdue', 'opening', E'Hi {first_name}! 👋\n\nFriendly reminder po from Cha Jewels — your layaway payment for INV #{invoice} was due on {due_date} ({days_ago}).', 2),
  ('reminder_overdue', 'opening', E'Hello {first_name}! 👋\n\nJust a reminder po that your layaway payment for INV #{invoice} was due on {due_date} ({days_ago}).', 3),
  ('reminder_overdue', 'opening', E'Hi {first_name}! 👋\n\nPaalala lang po from Cha Jewels — ang layaway payment mo for INV #{invoice} was due on {due_date} ({days_ago}).', 4),
  ('reminder_overdue', 'opening', E'Hello po {first_name}! 👋\n\nOur records show your layaway payment for INV #{invoice} was due on {due_date} ({days_ago}).', 5),
  ('reminder_overdue', 'opening', E'Hi {first_name}! 👋\n\nQuick reminder from Cha Jewels: your payment for INV #{invoice} was due on {due_date} ({days_ago}).', 6),
  ('reminder_overdue', 'closing', E'Thank you! 💎', 1),
  ('reminder_overdue', 'closing', E'Salamat po! 💎', 2),
  ('reminder_overdue', 'closing', E'Thank you po! 💎', 3),
  ('reminder_overdue', 'closing', E'Maraming salamat po! 💎', 4),
  ('reminder_overdue', 'closing', E'Thank you so much! 💎', 5),
  ('reminder_overdue', 'closing', E'Salamat po, {first_name}! 💎', 6),
  ('penalty_p1', 'opening', E'Hi {name}! 👋\n\nThis is a gentle reminder that your payment for:', 1),
  ('penalty_p1', 'opening', E'Hi {first_name}! 👋\n\nGentle reminder po that your payment for:', 2),
  ('penalty_p1', 'opening', E'Hello {first_name}! 👋\n\nJust a gentle reminder po — your payment for:', 3),
  ('penalty_p1', 'opening', E'Hi {first_name}! 👋\n\nPaalala lang po, your payment for:', 4),
  ('penalty_p1', 'opening', E'Hello po {first_name}! 👋\n\nThis is a friendly reminder that your payment for:', 5),
  ('penalty_p1', 'opening', E'Hi {first_name}! 👋\n\nA gentle reminder from Cha Jewels that your payment for:', 6),
  ('penalty_p1', 'closing', E'Thank you for your continued trust 💛', 1),
  ('penalty_p1', 'closing', E'Salamat po sa patuloy na tiwala 💛', 2),
  ('penalty_p1', 'closing', E'Thank you po for your continued trust 💛', 3),
  ('penalty_p1', 'closing', E'Maraming salamat po sa tiwala 💛', 4),
  ('penalty_p1', 'closing', E'We appreciate your continued trust 💛', 5),
  ('penalty_p1', 'closing', E'Thank you for always trusting us 💛', 6),
  ('penalty_p2', 'opening', E'Hi {name},\n\nYour payment for INV #{invoice} is now 14 days overdue (due {due_date}) and penalties are increasing.', 1),
  ('penalty_p2', 'opening', E'Hi {first_name},\n\nPaalala po: your payment for INV #{invoice} is now 14 days overdue (due {due_date}) and penalties are increasing.', 2),
  ('penalty_p2', 'opening', E'Hello {first_name},\n\nYour payment for INV #{invoice} is now 14 days overdue (due {due_date}), and penalties are increasing.', 3),
  ('penalty_p2', 'opening', E'Hi {first_name},\n\n14 days overdue na po ang payment mo for INV #{invoice} (due {due_date}), and penalties are increasing.', 4),
  ('penalty_p2', 'opening', E'Hello po {first_name},\n\nFollowing up on INV #{invoice}: your payment is now 14 days overdue (due {due_date}) and penalties are increasing.', 5),
  ('penalty_p2', 'opening', E'Hi {first_name},\n\nThis is a follow-up po — INV #{invoice} is now 14 days overdue (due {due_date}) and penalties are increasing.', 6),
  ('penalty_p2', 'closing', E'We kindly request your prompt attention to this matter.', 1),
  ('penalty_p2', 'closing', E'We kindly ask for your prompt attention to this po.', 2),
  ('penalty_p2', 'closing', E'Please give this your prompt attention.', 3),
  ('penalty_p2', 'closing', E'Pakiasikaso po agad — we kindly request your prompt attention.', 4),
  ('penalty_p2', 'closing', E'We would appreciate your prompt attention to this matter.', 5),
  ('penalty_p2', 'closing', E'Kindly attend to this promptly po.', 6),
  ('penalty_p3', 'opening', E'Hi {name},\n\nYour layaway payment for INV #{invoice} is now 1 month overdue (due {due_date}). Immediate action is advised.', 1),
  ('penalty_p3', 'opening', E'Hi {first_name},\n\nYour layaway payment for INV #{invoice} is now 1 month overdue (due {due_date}). Immediate action is advised po.', 2),
  ('penalty_p3', 'opening', E'Hello {first_name},\n\n1 month overdue na po ang layaway payment mo for INV #{invoice} (due {due_date}). Immediate action is advised.', 3),
  ('penalty_p3', 'opening', E'Hi {first_name},\n\nINV #{invoice} is now 1 month overdue (due {due_date}). We advise immediate action.', 4),
  ('penalty_p3', 'opening', E'Hello po {first_name},\n\nYour layaway payment for INV #{invoice} is now 1 month overdue (due {due_date}). Immediate action is advised.', 5),
  ('penalty_p3', 'opening', E'Hi {first_name},\n\nThis is a strong reminder: INV #{invoice} is now 1 month overdue (due {due_date}). Immediate action is advised.', 6),
  ('penalty_p3', 'closing', E'Please contact us to discuss your payment plan.', 1),
  ('penalty_p3', 'closing', E'Please message us po to discuss your payment plan.', 2),
  ('penalty_p3', 'closing', E'Kindly contact us to talk about your payment plan.', 3),
  ('penalty_p3', 'closing', E'Mag-message po kayo sa amin to discuss your payment plan.', 4),
  ('penalty_p3', 'closing', E'Please reach out to us to discuss your payment plan.', 5),
  ('penalty_p3', 'closing', E'Please contact us po so we can discuss your payment plan.', 6),
  ('penalty_p4', 'opening', E'Hi {name},\n\nIMPORTANT: Your payment for INV #{invoice} has been overdue for over 6 weeks (due {due_date}).', 1),
  ('penalty_p4', 'opening', E'Hi {first_name},\n\nIMPORTANT po: your payment for INV #{invoice} has been overdue for over 6 weeks (due {due_date}).', 2),
  ('penalty_p4', 'opening', E'Hello {first_name},\n\nIMPORTANT: INV #{invoice} has been overdue for over 6 weeks (due {due_date}).', 3),
  ('penalty_p4', 'opening', E'Hi {first_name},\n\nIMPORTANT: Mahigit 6 weeks na pong overdue ang payment mo for INV #{invoice} (due {due_date}).', 4),
  ('penalty_p4', 'opening', E'Hello po {first_name},\n\nIMPORTANT: Your payment for INV #{invoice} is now more than 6 weeks overdue (due {due_date}).', 5),
  ('penalty_p4', 'opening', E'Hi {first_name},\n\nIMPORTANT — escalation notice: your payment for INV #{invoice} has been overdue for over 6 weeks (due {due_date}).', 6),
  ('penalty_p4', 'closing', E'Please settle immediately to avoid account risk.', 1),
  ('penalty_p4', 'closing', E'Please settle immediately po to avoid account risk.', 2),
  ('penalty_p4', 'closing', E'Pakisettle po agad to avoid account risk.', 3),
  ('penalty_p4', 'closing', E'Kindly settle immediately to avoid putting your account at risk.', 4),
  ('penalty_p4', 'closing', E'Immediate settlement is needed to avoid account risk.', 5),
  ('penalty_p4', 'closing', E'Please settle now to avoid account risk.', 6),
  ('penalty_p5', 'opening', E'Dear {name},\n\nYour layaway payment for INV #{invoice} is now 2 months overdue (due {due_date}).', 1),
  ('penalty_p5', 'opening', E'Dear {first_name},\n\nYour layaway payment for INV #{invoice} is now 2 months overdue (due {due_date}).', 2),
  ('penalty_p5', 'opening', E'Dear {name},\n\n2 months overdue na po ang layaway payment mo for INV #{invoice} (due {due_date}).', 3),
  ('penalty_p5', 'opening', E'Dear {first_name},\n\nURGENT: INV #{invoice} is now 2 months overdue (due {due_date}).', 4),
  ('penalty_p5', 'opening', E'Dear {name},\n\nThis is an urgent reminder po — your layaway payment for INV #{invoice} is now 2 months overdue (due {due_date}).', 5),
  ('penalty_p5', 'opening', E'Dear {first_name},\n\nYour layaway payment for INV #{invoice} has been overdue for 2 months (due {due_date}).', 6),
  ('penalty_p5', 'closing', E'Your account is significantly overdue with penalties. Immediate payment is required.', 1),
  ('penalty_p5', 'closing', E'Your account is significantly overdue with penalties. Immediate payment is required po.', 2),
  ('penalty_p5', 'closing', E'Malaki na po ang overdue at penalties ng account mo. Immediate payment is required.', 3),
  ('penalty_p5', 'closing', E'With penalties, your account is significantly overdue. Payment is required immediately.', 4),
  ('penalty_p5', 'closing', E'Your account is significantly overdue and has penalties. Immediate payment is required.', 5),
  ('penalty_p5', 'closing', E'Significantly overdue na po ang account mo with penalties. Kailangan na po ang immediate payment.', 6),
  ('penalty_p6', 'opening', E'Dear {name},\n\nThis is your FINAL WARNING regarding INV #{invoice} (due {due_date}).', 1),
  ('penalty_p6', 'opening', E'Dear {first_name},\n\nThis is your FINAL WARNING regarding INV #{invoice} (due {due_date}).', 2),
  ('penalty_p6', 'opening', E'Dear {name},\n\nFINAL WARNING po ito regarding INV #{invoice} (due {due_date}).', 3),
  ('penalty_p6', 'opening', E'Dear {first_name},\n\nPlease treat this as your FINAL WARNING for INV #{invoice} (due {due_date}).', 4),
  ('penalty_p6', 'opening', E'Dear {name},\n\nFINAL WARNING regarding your layaway INV #{invoice} (due {due_date}).', 5),
  ('penalty_p6', 'opening', E'Dear {first_name},\n\nWe are sending this FINAL WARNING regarding INV #{invoice} (due {due_date}).', 6),
  ('penalty_p6', 'closing', E'Further action will be taken if not settled immediately.', 1),
  ('penalty_p6', 'closing', E'Further action will be taken if this is not settled immediately.', 2),
  ('penalty_p6', 'closing', E'Kung hindi po ma-settle agad, further action will be taken.', 3),
  ('penalty_p6', 'closing', E'If not settled immediately, further action will be taken.', 4),
  ('penalty_p6', 'closing', E'Please settle immediately — otherwise, further action will be taken.', 5),
  ('penalty_p6', 'closing', E'Further action will follow if this is not settled immediately po.', 6),
  ('penalty_p7', 'opening', E'Dear {name},\n\nYour layaway account for INV #{invoice} is 3 months overdue (due {due_date}) and at HIGH RISK of forfeiture.', 1),
  ('penalty_p7', 'opening', E'Dear {first_name},\n\nYour layaway account for INV #{invoice} is 3 months overdue (due {due_date}) and at HIGH RISK of forfeiture.', 2),
  ('penalty_p7', 'opening', E'Dear {name},\n\n3 months overdue na po ang layaway account mo for INV #{invoice} (due {due_date}) and it is at HIGH RISK of forfeiture.', 3),
  ('penalty_p7', 'opening', E'Dear {first_name},\n\nCRITICAL: INV #{invoice} is 3 months overdue (due {due_date}) and at HIGH RISK of forfeiture.', 4),
  ('penalty_p7', 'opening', E'Dear {name},\n\nYour layaway account (INV #{invoice}) is now 3 months overdue (due {due_date}) and is at HIGH RISK of forfeiture.', 5),
  ('penalty_p7', 'opening', E'Dear {first_name},\n\nThis is a critical escalation po: INV #{invoice} is 3 months overdue (due {due_date}) and at HIGH RISK of forfeiture.', 6),
  ('penalty_p7', 'closing', E'Please contact us IMMEDIATELY to resolve your account.', 1),
  ('penalty_p7', 'closing', E'Please contact us IMMEDIATELY po to resolve your account.', 2),
  ('penalty_p7', 'closing', E'Mag-message po kayo IMMEDIATELY para ma-resolve ang account mo.', 3),
  ('penalty_p7', 'closing', E'Contact us IMMEDIATELY so we can resolve your account.', 4),
  ('penalty_p7', 'closing', E'Kindly reach out to us IMMEDIATELY to resolve your account.', 5),
  ('penalty_p7', 'closing', E'Please message us IMMEDIATELY to resolve your account.', 6),
  ('penalty_p8', 'opening', E'Dear {name},\n\nYour layaway account for INV #{invoice} has been overdue since {due_date} and is SUBJECT FOR FORFEITURE if not settled immediately.', 1),
  ('penalty_p8', 'opening', E'Dear {first_name},\n\nYour layaway account for INV #{invoice} has been overdue since {due_date} and is SUBJECT FOR FORFEITURE if not settled immediately.', 2),
  ('penalty_p8', 'opening', E'Dear {name},\n\nOverdue na po since {due_date} ang layaway account mo for INV #{invoice}, and it is SUBJECT FOR FORFEITURE if not settled immediately.', 3),
  ('penalty_p8', 'opening', E'Dear {first_name},\n\nFINAL NOTICE: INV #{invoice} has been overdue since {due_date} and is SUBJECT FOR FORFEITURE if not settled immediately.', 4),
  ('penalty_p8', 'opening', E'Dear {name},\n\nINV #{invoice} has been overdue since {due_date}. It is SUBJECT FOR FORFEITURE if not settled immediately.', 5),
  ('penalty_p8', 'opening', E'Dear {first_name},\n\nPlease be advised po: your layaway account for INV #{invoice} has been overdue since {due_date} and is SUBJECT FOR FORFEITURE if not settled immediately.', 6),
  ('penalty_p8', 'closing', E'This is your final notice before permanent account forfeiture.', 1),
  ('penalty_p8', 'closing', E'This is your final notice po before permanent account forfeiture.', 2),
  ('penalty_p8', 'closing', E'Ito na po ang final notice bago ang permanent account forfeiture.', 3),
  ('penalty_p8', 'closing', E'Please note: this is your final notice before permanent account forfeiture.', 4),
  ('penalty_p8', 'closing', E'This serves as your final notice before permanent account forfeiture.', 5),
  ('penalty_p8', 'closing', E'Final notice po ito before your account is permanently forfeited.', 6)
) AS v(message_type, part, body, sort)
WHERE NOT EXISTS (
  SELECT 1 FROM public.message_lines m WHERE m.message_type = v.message_type AND m.part = v.part
);
COMMIT;
