-- Minimal copies of the live tables (column types from live information_schema, 2026-10-04).
CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid', true), '')::uuid $$;
CREATE TABLE public.audit_logs (id uuid DEFAULT gen_random_uuid(), entity_type text, entity_id uuid, action text, old_value_json jsonb, new_value_json jsonb, performed_by_user_id uuid, created_at timestamp with time zone DEFAULT now());
CREATE TABLE public.cash_orders (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, invoice_number text, customer_id uuid, currency text, total_amount numeric(12,2), total_paid numeric(12,2), remaining_balance numeric(12,2), status text, item_description text, loyalty_jpy_amount numeric(12,2), order_date date, notes text, completed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), is_test boolean DEFAULT false, source_channel text, shopify_order_id text, payment_status text, ship_to_address_id uuid, quote_id uuid, ship_to_snapshot jsonb, ready_confirmed_at timestamp with time zone);
CREATE TABLE public.cash_payments (id uuid DEFAULT gen_random_uuid(), cash_order_id uuid, amount_paid numeric(12,2), currency text, date_paid date, payment_method text, reference_number text, remarks text, entered_by_user_id uuid, submitted_by_type text, submitted_by_name text, voided_at timestamp with time zone, voided_by_user_id uuid, void_reason text, created_at timestamp with time zone DEFAULT now(), provider_capture_id text);
CREATE TABLE public.checkout_quotes (id uuid DEFAULT gen_random_uuid(), customer_id uuid);
CREATE TABLE public.csr_notifications (id uuid DEFAULT gen_random_uuid(), account_id uuid, customer_id uuid);
CREATE TABLE public.customers (id uuid DEFAULT gen_random_uuid(), customer_code text, full_name text, mobile_number text, email text, facebook_name text, is_test boolean DEFAULT false);
CREATE TABLE public.extension_requests (id uuid DEFAULT gen_random_uuid(), account_id uuid, customer_id uuid, portal_token text);
CREATE TABLE public.layaway_accounts (id uuid DEFAULT gen_random_uuid(), customer_id uuid, invoice_number text, total_amount numeric(15,2), order_date date, status text, completed_at timestamp with time zone, loyalty_jpy_amount numeric, source_channel text, quote_id uuid);
CREATE TABLE public.loyalty_award_claims (source_kind text, source_id uuid, claimed_at timestamp with time zone DEFAULT now(), transaction_id uuid);
CREATE TABLE public.loyalty_members (id uuid DEFAULT gen_random_uuid(), customer_id uuid, cumulative_spend_jpy numeric, earned_tier_id uuid, current_tier_id uuid, is_downgraded boolean DEFAULT false, total_points_earned numeric, remaining_points numeric, enrolled_at timestamp with time zone DEFAULT now(), downgrade_spend_baseline numeric, spend_baseline_jpy numeric);
CREATE TABLE public.loyalty_point_lots (id uuid DEFAULT gen_random_uuid(), source_type text, source_reference text);
CREATE TABLE public.loyalty_redemptions (id uuid DEFAULT gen_random_uuid(), invoice_number text, account_id uuid, cash_order_id uuid, status text);
CREATE TABLE public.loyalty_tiers (id uuid DEFAULT gen_random_uuid(), name text, min_spend_jpy numeric, points_multiplier numeric, requalify_spend_jpy numeric);
CREATE TABLE public.loyalty_transactions (id uuid DEFAULT gen_random_uuid(), account_id uuid, cash_order_id uuid, transaction_type text, invoice_number text);
CREATE TABLE public.paidy_cases (id uuid DEFAULT gen_random_uuid(), kind text, status text, cash_order_id uuid, paidy_payment_row uuid, paidy_payment_id text);
CREATE TABLE public.paidy_checkout_attempts (id uuid DEFAULT gen_random_uuid(), cash_order_id uuid, customer_id uuid, status text, amount_jpy numeric(12,2), started_at timestamp with time zone DEFAULT now(), expires_at timestamp with time zone);
CREATE TABLE public.paidy_payments (id uuid DEFAULT gen_random_uuid(), cash_order_id uuid, customer_id uuid, paidy_payment_id text, status text, test boolean DEFAULT false, amount_jpy numeric(12,2), authorized_at timestamp with time zone DEFAULT now(), expires_at timestamp with time zone);
CREATE TABLE public.payment_submission_allocations (id uuid DEFAULT gen_random_uuid(), submission_id uuid, account_id uuid);
CREATE TABLE public.payment_submissions (id uuid DEFAULT gen_random_uuid(), customer_id uuid, account_id uuid, submitted_amount numeric(15,2), payment_method text, status text, confirmed_payment_id uuid, portal_token text, updated_at timestamp with time zone DEFAULT now(), submission_type text, cash_order_id uuid, paidy_payment_id uuid);
CREATE TABLE public.payments (id uuid DEFAULT gen_random_uuid(), account_id uuid, created_at timestamp with time zone DEFAULT now(), voided_at timestamp with time zone, reference_number text, remarks text);
CREATE TABLE public.service_jobs (id uuid DEFAULT gen_random_uuid(), invoice_number text, account_type text, customer_id uuid);
CREATE TABLE public.service_requests (id uuid DEFAULT gen_random_uuid(), customer_id uuid, cash_order_id uuid, layaway_account_id uuid);
CREATE TABLE public.store_credit_lots (id uuid DEFAULT gen_random_uuid(), source_account_id uuid, source_cash_order_id uuid);
CREATE TABLE public.store_credit_transactions (id uuid DEFAULT gen_random_uuid(), account_id uuid, cash_order_id uuid);
CREATE TABLE public.system_settings (id uuid DEFAULT gen_random_uuid(), key text, value jsonb);
CREATE FUNCTION public.has_permission(uuid, text) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT true $$;
CREATE FUNCTION public.address_snapshot(uuid) RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT '{}'::jsonb $$;
