export const ROUTES = {
  DASHBOARD: "/",
  ACCOUNTS: "/accounts",
  NEW_ACCOUNT: "/accounts/new",
  ACCOUNT_DETAIL: "/accounts/:id",
  CUSTOMERS: "/customers",
  CUSTOMER_DETAIL: "/customers/:customerId",
  MONITORING: "/monitoring",
  FINANCE: "/finance",
  WAIVERS: "/waivers",
  ADMIN_AUDIT: "/admin-audit",
  ADMIN_ACTIVITY: "/admin-activity",
  SETTINGS: "/settings",
  PAYMENT_SUBMISSIONS: "/payment-submissions",
  PAYMENT_VAULT: "/admin/payment-vault",
  PAYMENT_PROOFS: "/payment-proofs",
  PAYMENTS_HUB: "/payments-hub",
  BULK_PAYMENT_IMPORT: "/bulk-payment-import",
  PROMOTIONS: "/promotions",
  LOYALTY_ADMIN: "/loyalty/admin",
  LOYALTY_REDEMPTIONS: "/loyalty/redemptions",
  EXECUTIVE_DASHBOARD: "/executive-dashboard",
};
