/* eslint-disable @typescript-eslint/no-explicit-any -- the draft tables and several columns are not in types.ts yet (regenerated by Lovable); rows are shaped into typed records right here. */
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { OPEN_SERVICE_REQUEST_STATUSES, serviceRequests } from '@/components/services/service-request-types';
import type { Currency } from '@/lib/types';
import type { ParkKind } from '@/lib/web-park';

/**
 * Website orders PR 5 — the park area's reads (docs/WEB-ORDER-DRAFTS.md "PR 5").
 *
 * Drafts are readable only by holders of confirm_web_order_ready (RLS on
 * web_order_drafts); every hook here is enabled only for them. The keys
 * 'web-drafts' and 'web-park' are in CORE_KEYS (use-supabase-data.ts), so a
 * realtime change on cash_orders / layaway_accounts / staff_notifications (a
 * new draft rings a bell) refetches them; the 60s poll covers the rest, since
 * the draft tables are not in the realtime publication.
 */

const POLL = 60_000;
// The untyped tables (types.ts regenerates on Lovable's next push); cast at the call site.
const db = supabase as any;

export interface WebDraftRow {
  id: string;
  web_reference: string;
  customer_id: string;
  customer_name: string;
  customer_is_test: boolean;
  mode: 'full' | 'layaway';
  term_months: number | null;
  currency: Currency;
  total: number;
  shipping_pending: boolean;
  country: string | null;
  status: 'to_confirm' | 'confirmed' | 'declined' | 'expired';
  decline_reason: string | null;
  decided_at: string | null;
  cash_order_id: string | null;
  layaway_account_id: string | null;
  created_at: string;
  open_service_requests: number;
}

const DRAFT_SELECT =
  'id, web_reference, customer_id, mode, term_months, settlement_currency, total, shipping_jpy, country, status, decline_reason, decided_at, cash_order_id, layaway_account_id, created_at, customers(full_name, is_test)';

function shapeDraft(r: any, requests: Map<string, number>): WebDraftRow {
  return {
    id: r.id,
    web_reference: r.web_reference,
    customer_id: r.customer_id,
    customer_name: r.customers?.full_name ?? 'A website customer',
    customer_is_test: r.customers?.is_test === true,
    mode: r.mode === 'layaway' ? 'layaway' : 'full',
    term_months: r.term_months ?? null,
    currency: r.settlement_currency === 'PHP' ? 'PHP' : 'JPY',
    total: Number(r.total ?? 0),
    shipping_pending: r.shipping_jpy === null || r.shipping_jpy === undefined,
    country: r.country ?? null,
    status: r.status,
    decline_reason: r.decline_reason ?? null,
    decided_at: r.decided_at ?? null,
    cash_order_id: r.cash_order_id ?? null,
    layaway_account_id: r.layaway_account_id ?? null,
    created_at: r.created_at,
    open_service_requests: requests.get(r.id) ?? 0,
  };
}

async function openRequestsByDraft(ids: string[]): Promise<Map<string, number>> {
  const out = new Map<string, number>();
  if (ids.length === 0) return out;
  const { data, error } = await serviceRequests()
    .select('id, web_draft_id')
    .in('web_draft_id', ids)
    .in('status', OPEN_SERVICE_REQUEST_STATUSES);
  if (error) throw error;
  for (const r of (data ?? []) as { web_draft_id: string | null }[]) {
    if (r.web_draft_id) out.set(r.web_draft_id, (out.get(r.web_draft_id) ?? 0) + 1);
  }
  return out;
}

/**
 * Drafts. 'open' = to_confirm, oldest first (the queue); 'closed' = declined /
 * expired, newest first. Optionally one customer's only.
 */
export function useWebDrafts(scope: 'open' | 'closed', enabled = true, customerId?: string) {
  return useQuery({
    queryKey: ['web-drafts', scope, customerId ?? 'all'],
    enabled,
    staleTime: 30_000,
    refetchInterval: POLL,
    refetchOnWindowFocus: true,
    queryFn: async (): Promise<WebDraftRow[]> => {
      let q = db.from('web_order_drafts').select(DRAFT_SELECT);
      if (customerId) q = q.eq('customer_id', customerId);
      q = scope === 'open'
        ? q.eq('status', 'to_confirm').order('created_at', { ascending: true }).limit(200)
        : q.in('status', ['declined', 'expired']).order('decided_at', { ascending: false }).limit(100);
      const { data, error } = await q;
      if (error) throw error;
      const rows = (data ?? []) as any[];
      const requests = scope === 'open' ? await openRequestsByDraft(rows.map((r) => r.id)) : new Map<string, number>();
      return rows.map((r) => shapeDraft(r, requests));
    },
  });
}

export interface ParkedOrderRow {
  kind: ParkKind;
  id: string;
  reference: string;
  customer_id: string | null;
  customer_name: string;
  customer_is_test: boolean;
  currency: Currency;
  total_amount: number;
  /** What the customer must pay now: a cash order's balance, a plan's deposit. */
  amount_due: number;
  plan_months: number | null;
  status: string;
  transfer_due_at: string | null;
  created_at: string;
  reminder_sent: boolean;
  pending_submission: boolean;
}

const LAYAWAY_LIVE_EXCLUDED = '(completed,cancelled,forfeited,final_forfeited)';
const CASH_LIVE_EXCLUDED = '(completed,cancelled,expired)';

function shapeOrder(r: any, kind: ParkKind, sent: Set<string>, pending: Set<string>): ParkedOrderRow {
  return {
    kind,
    id: r.id,
    reference: r.web_reference ?? r.invoice_number ?? '?',
    customer_id: r.customer_id ?? null,
    customer_name: r.customers?.full_name ?? 'A website customer',
    customer_is_test: r.customers?.is_test === true,
    currency: r.currency === 'PHP' ? 'PHP' : 'JPY',
    total_amount: Number(r.total_amount ?? 0),
    amount_due: Number(kind === 'layaway' ? r.downpayment_amount ?? 0 : r.remaining_balance ?? 0),
    plan_months: kind === 'layaway' ? Number(r.payment_plan_months ?? 0) || null : null,
    status: String(r.status ?? ''),
    transfer_due_at: r.transfer_due_at ?? null,
    created_at: r.created_at,
    reminder_sent: sent.has(r.id),
    pending_submission: pending.has(r.id),
  };
}

/**
 * Confirmed web orders with no payment yet (web_released_at NULL), still live —
 * the "Awaiting payment" tab. Nearest deadline first.
 */
export function useWebAwaitingPayment(enabled = true) {
  return useQuery({
    queryKey: ['web-park', 'awaiting'],
    enabled,
    staleTime: 30_000,
    refetchInterval: POLL,
    refetchOnWindowFocus: true,
    queryFn: async (): Promise<ParkedOrderRow[]> => {
      const [cash, lay] = await Promise.all([
        db.from('cash_orders')
          .select('id, web_reference, invoice_number, customer_id, currency, total_amount, remaining_balance, status, transfer_due_at, created_at, customers(full_name, is_test)')
          .eq('source_channel', 'web').is('web_released_at', null).not('ready_confirmed_at', 'is', null)
          .not('status', 'in', CASH_LIVE_EXCLUDED)
          .limit(200),
        db.from('layaway_accounts')
          .select('id, web_reference, invoice_number, customer_id, currency, total_amount, downpayment_amount, payment_plan_months, status, transfer_due_at, created_at, customers(full_name, is_test)')
          .eq('source_channel', 'web').is('web_released_at', null).not('ready_confirmed_at', 'is', null)
          .not('status', 'in', LAYAWAY_LIVE_EXCLUDED)
          .limit(200),
      ]);
      if (cash.error) throw cash.error;
      if (lay.error) throw lay.error;
      const cashRows = (cash.data ?? []) as any[];
      const layRows = (lay.data ?? []) as any[];
      const cashIds = cashRows.map((r) => r.id);
      const layIds = layRows.map((r) => r.id);
      const allIds = [...cashIds, ...layIds];

      const sent = new Set<string>();
      const pending = new Set<string>();
      if (allIds.length > 0) {
        const [rem, subCash, subLay] = await Promise.all([
          db.from('web_payment_reminders').select('entity_id').in('entity_id', allIds).eq('status', 'sent'),
          cashIds.length
            ? db.from('payment_submissions').select('cash_order_id').in('cash_order_id', cashIds).in('status', ['submitted', 'under_review'])
            : Promise.resolve({ data: [], error: null }),
          layIds.length
            ? db.from('payment_submissions').select('account_id').in('account_id', layIds).in('status', ['submitted', 'under_review'])
            : Promise.resolve({ data: [], error: null }),
        ]);
        if (rem.error) throw rem.error;
        if (subCash.error) throw subCash.error;
        if (subLay.error) throw subLay.error;
        for (const r of (rem.data ?? []) as any[]) sent.add(r.entity_id);
        for (const r of (subCash.data ?? []) as any[]) if (r.cash_order_id) pending.add(r.cash_order_id);
        for (const r of (subLay.data ?? []) as any[]) if (r.account_id) pending.add(r.account_id);
      }

      const byDeadline = (a: ParkedOrderRow, b: ParkedOrderRow) =>
        (a.transfer_due_at ?? '9999').localeCompare(b.transfer_due_at ?? '9999');
      return [
        ...cashRows.map((r) => shapeOrder(r, 'cash_order', sent, pending)),
        ...layRows.map((r) => shapeOrder(r, 'layaway', sent, pending)),
      ].sort(byDeadline);
    },
  });
}

/** Web orders cancelled / expired / forfeited without ever being paid — the Closed tab (W2-2). */
export function useWebClosedUnpaid(enabled = true) {
  return useQuery({
    queryKey: ['web-park', 'closed'],
    enabled,
    staleTime: 60_000,
    refetchOnWindowFocus: false,
    queryFn: async (): Promise<ParkedOrderRow[]> => {
      const [cash, lay] = await Promise.all([
        db.from('cash_orders')
          .select('id, web_reference, invoice_number, customer_id, currency, total_amount, remaining_balance, status, transfer_due_at, created_at, customers(full_name, is_test)')
          .eq('source_channel', 'web').is('web_released_at', null).in('status', ['cancelled', 'expired'])
          .order('created_at', { ascending: false }).limit(100),
        db.from('layaway_accounts')
          .select('id, web_reference, invoice_number, customer_id, currency, total_amount, downpayment_amount, payment_plan_months, status, transfer_due_at, created_at, customers(full_name, is_test)')
          .eq('source_channel', 'web').is('web_released_at', null).in('status', ['cancelled', 'forfeited', 'final_forfeited'])
          .order('created_at', { ascending: false }).limit(100),
      ]);
      if (cash.error) throw cash.error;
      if (lay.error) throw lay.error;
      const none = new Set<string>();
      return [
        ...((cash.data ?? []) as any[]).map((r) => shapeOrder(r, 'cash_order', none, none)),
        ...((lay.data ?? []) as any[]).map((r) => shapeOrder(r, 'layaway', none, none)),
      ].sort((a, b) => b.created_at.localeCompare(a.created_at));
    },
  });
}

/** Everything the park-area actions change — refetch after a decline. */
export function useInvalidateWebPark() {
  const qc = useQueryClient();
  return () => {
    for (const key of ['web-drafts', 'web-park', 'website-products', 'staff-notifications']) {
      qc.invalidateQueries({ queryKey: [key] });
    }
  };
}

/** "Can't supply" on a draft — confirm-web-draft { action: 'decline' }. Throws staff-readable words. */
export async function declineWebDraft(draftId: string, reason: string): Promise<void> {
  const { error } = await supabase.functions.invoke('confirm-web-draft', {
    body: { action: 'decline', draft_id: draftId, reason: reason.trim() },
  });
  if (!error) return;
  let code = '';
  try {
    const ctx = (error as any)?.context;
    const body = ctx && typeof ctx.json === 'function' ? await ctx.json() : null;
    code = String(body?.error ?? '');
  } catch { /* fall through */ }
  if (code === 'not_open') throw new Error('This order was already confirmed, declined or cancelled.');
  if (code === 'reason_required') throw new Error('Write the reason the customer will be told.');
  if (code === 'permission_denied') throw new Error('You do not have permission to decline website orders.');
  throw new Error(code || (error as Error).message || 'Could not decline the order.');
}
