// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying MCP connectivity.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/search-customers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_customers_default = defineTool2({
  name: "search_customers",
  title: "Search customers",
  description: "Search Cha Jewels customers by full name, email, customer code, or mobile number. Returns up to 20 matches. Requires an authenticated internal user (RLS-enforced).",
  inputSchema: {
    query: z2.string().min(2).describe("Partial name, email, customer code (CJ-YYYY-XXXXX), or mobile number.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const q = query.trim();
    const { data, error } = await supabase.from("customers").select("id, customer_code, full_name, email, mobile_number, location, is_test").or(
      `full_name.ilike.%${q}%,email.ilike.%${q}%,customer_code.ilike.%${q}%,mobile_number.ilike.%${q}%`
    ).eq("is_test", false).limit(20);
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-account.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_account_default = defineTool3({
  name: "get_account_by_invoice",
  title: "Get layaway account by invoice",
  description: "Look up a layaway account by its numeric invoice number. Returns account totals, status, customer, and current payment schedule. Requires an authenticated internal user (RLS-enforced).",
  inputSchema: {
    invoice_number: z3.string().min(1).describe("Invoice number (numeric string, e.g. '19115').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ invoice_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: account, error } = await supabase.from("layaway_accounts").select(
      "id, invoice_number, status, currency, total_amount, total_paid, remaining_balance, downpayment_amount, payment_plan_months, order_date, is_trade, customer:customers(id, customer_code, full_name, email, mobile_number)"
    ).eq("invoice_number", invoice_number.trim()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Query failed: ${error.message}` }], isError: true };
    }
    if (!account) {
      return {
        content: [{ type: "text", text: `No account found for invoice ${invoice_number}` }]
      };
    }
    const { data: schedule } = await supabase.from("layaway_schedule").select("installment_number, due_date, base_installment_amount, penalty_amount, carried_amount, paid_amount, total_due_amount, status").eq("account_id", account.id).order("installment_number", { ascending: true });
    const result = { account, schedule: schedule ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pfoicalpzdcmyxzvwyhz";
var mcp_default = defineMcp({
  name: "cha-jewels-hub-mcp",
  title: "Cha Jewels Hub MCP",
  version: "0.1.0",
  instructions: "Tools for Cha Jewels Hub \u2014 the internal layaway management system. Use `echo` to verify connectivity, `search_customers` to look up customers by name/email/code/mobile, and `get_account_by_invoice` to fetch a layaway account with its payment schedule. All data access runs as the signed-in internal user under Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, search_customers_default, get_account_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
