-- RECORD-ONLY (repo structure catch-up, owner go 2026-10-09).
--
-- RLS policies that exist on live on the tables recorded by
-- 20260705230001_record_live_only_structure.sql, created in the SQL Editor and
-- never committed. Each is created ONLY IF MISSING (by table + name), so on
-- live this changes nothing; on an empty database it rebuilds them.
--
-- Written in the bare-call form live held before 20261024100000 (the next
-- migration), which wraps every call in a scalar sub-select and so turns these
-- back into live's exact text. Placed here, not with the tables, because some
-- policies call has_permission(), which does not exist until later.
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='cash_order_items' AND policyname='Customers can view own cash order items') THEN EXECUTE 'CREATE POLICY "Customers can view own cash order items" ON public.cash_order_items AS PERMISSIVE FOR SELECT TO "authenticated" USING ((cash_order_id IN ( SELECT co.id
   FROM cash_orders co
  WHERE (co.customer_id IN ( SELECT c.id
           FROM customers c
          WHERE (c.auth_user_id = auth.uid()))))))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='cash_order_items' AND policyname='admin_all_cash_order_items') THEN EXECUTE 'CREATE POLICY "admin_all_cash_order_items" ON public.cash_order_items AS PERMISSIVE FOR ALL TO PUBLIC USING (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='cash_order_items' AND policyname='order_creators_insert_cash_order_items') THEN EXECUTE 'CREATE POLICY "order_creators_insert_cash_order_items" ON public.cash_order_items AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((has_role(auth.uid(), ''admin''::app_role) OR has_role(auth.uid(), ''finance''::app_role) OR has_role(auth.uid(), ''staff''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='cash_order_items' AND policyname='staff_finance_read_cash_order_items') THEN EXECUTE 'CREATE POLICY "staff_finance_read_cash_order_items" ON public.cash_order_items AS PERMISSIVE FOR SELECT TO PUBLIC USING ((has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='message_lines' AND policyname='Admins can update message lines') THEN EXECUTE 'CREATE POLICY "Admins can update message lines" ON public.message_lines AS PERMISSIVE FOR UPDATE TO "authenticated" USING (has_role(auth.uid(), ''admin''::app_role)) WITH CHECK (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='message_lines' AND policyname='Staff can view message lines') THEN EXECUTE 'CREATE POLICY "Staff can view message lines" ON public.message_lines AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='newsletter_subscribers' AND policyname='Staff can manage newsletter subscribers') THEN EXECUTE 'CREATE POLICY "Staff can manage newsletter subscribers" ON public.newsletter_subscribers AS PERMISSIVE FOR ALL TO "authenticated" USING (is_staff(auth.uid())) WITH CHECK (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='newsletter_subscribers' AND policyname='Staff can view newsletter subscribers') THEN EXECUTE 'CREATE POLICY "Staff can view newsletter subscribers" ON public.newsletter_subscribers AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='newsletter_subscribers' AND policyname='Website catalog managers can unsubscribe') THEN EXECUTE 'CREATE POLICY "Website catalog managers can unsubscribe" ON public.newsletter_subscribers AS PERMISSIVE FOR UPDATE TO "authenticated" USING (has_permission(auth.uid(), ''manage_website_catalog''::text)) WITH CHECK (has_permission(auth.uid(), ''manage_website_catalog''::text))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='newsletter_subscribers' AND policyname='Website catalog managers can view subscribers') THEN EXECUTE 'CREATE POLICY "Website catalog managers can view subscribers" ON public.newsletter_subscribers AS PERMISSIVE FOR SELECT TO "authenticated" USING (has_permission(auth.uid(), ''manage_website_catalog''::text))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='pancake_events' AND policyname='Staff can read pancake_events') THEN EXECUTE 'CREATE POLICY "Staff can read pancake_events" ON public.pancake_events AS PERMISSIVE FOR SELECT TO "authenticated" USING ((has_role(auth.uid(), ''admin''::app_role) OR has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role) OR has_role(auth.uid(), ''csr''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='pancake_events' AND policyname='Staff can update pancake_events status') THEN EXECUTE 'CREATE POLICY "Staff can update pancake_events status" ON public.pancake_events AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((has_role(auth.uid(), ''admin''::app_role) OR has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role) OR has_role(auth.uid(), ''csr''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='product_reviews' AND policyname='Moderators can update product reviews') THEN EXECUTE 'CREATE POLICY "Moderators can update product reviews" ON public.product_reviews AS PERMISSIVE FOR UPDATE TO "authenticated" USING (has_permission(auth.uid(), ''moderate_reviews''::text)) WITH CHECK (has_permission(auth.uid(), ''moderate_reviews''::text))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='product_reviews' AND policyname='Staff can view product reviews') THEN EXECUTE 'CREATE POLICY "Staff can view product reviews" ON public.product_reviews AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='products' AND policyname='authenticated_read_products') THEN EXECUTE 'CREATE POLICY "authenticated_read_products" ON public.products AS PERMISSIVE FOR SELECT TO "authenticated" USING (true)'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='review_invites' AND policyname='Invite senders can create review invites') THEN EXECUTE 'CREATE POLICY "Invite senders can create review invites" ON public.review_invites AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((has_permission(auth.uid(), ''send_review_invite''::text) AND (created_by = auth.uid())))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='review_invites' AND policyname='Invite senders can revoke review invites') THEN EXECUTE 'CREATE POLICY "Invite senders can revoke review invites" ON public.review_invites AS PERMISSIVE FOR UPDATE TO "authenticated" USING (has_permission(auth.uid(), ''send_review_invite''::text)) WITH CHECK (has_permission(auth.uid(), ''send_review_invite''::text))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='review_invites' AND policyname='Staff can view review invites') THEN EXECUTE 'CREATE POLICY "Staff can view review invites" ON public.review_invites AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='service_requests' AND policyname='Staff can manage service requests') THEN EXECUTE 'CREATE POLICY "Staff can manage service requests" ON public.service_requests AS PERMISSIVE FOR ALL TO "authenticated" USING (is_staff(auth.uid())) WITH CHECK (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='service_requests' AND policyname='Staff can view service requests') THEN EXECUTE 'CREATE POLICY "Staff can view service requests" ON public.service_requests AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='shopify_webhook_events' AND policyname='admin_read_shopify_webhook_events') THEN EXECUTE 'CREATE POLICY "admin_read_shopify_webhook_events" ON public.shopify_webhook_events AS PERMISSIVE FOR SELECT TO PUBLIC USING (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_lots' AND policyname='admin_all_store_credit_lots') THEN EXECUTE 'CREATE POLICY "admin_all_store_credit_lots" ON public.store_credit_lots AS PERMISSIVE FOR ALL TO PUBLIC USING (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_lots' AND policyname='staff_finance_read_store_credit_lots') THEN EXECUTE 'CREATE POLICY "staff_finance_read_store_credit_lots" ON public.store_credit_lots AS PERMISSIVE FOR SELECT TO PUBLIC USING ((has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_reconciliation' AND policyname='admin_all_sc_recon') THEN EXECUTE 'CREATE POLICY "admin_all_sc_recon" ON public.store_credit_reconciliation AS PERMISSIVE FOR ALL TO PUBLIC USING (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_reconciliation' AND policyname='staff_finance_read_sc_recon') THEN EXECUTE 'CREATE POLICY "staff_finance_read_sc_recon" ON public.store_credit_reconciliation AS PERMISSIVE FOR SELECT TO PUBLIC USING ((has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_shopify_sync' AND policyname='admin_all_sc_shopify_sync') THEN EXECUTE 'CREATE POLICY "admin_all_sc_shopify_sync" ON public.store_credit_shopify_sync AS PERMISSIVE FOR ALL TO PUBLIC USING (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_shopify_sync' AND policyname='staff_finance_read_sc_shopify_sync') THEN EXECUTE 'CREATE POLICY "staff_finance_read_sc_shopify_sync" ON public.store_credit_shopify_sync AS PERMISSIVE FOR SELECT TO PUBLIC USING ((has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_transactions' AND policyname='admin_all_store_credit_txn') THEN EXECUTE 'CREATE POLICY "admin_all_store_credit_txn" ON public.store_credit_transactions AS PERMISSIVE FOR ALL TO PUBLIC USING (has_role(auth.uid(), ''admin''::app_role))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='store_credit_transactions' AND policyname='staff_finance_read_store_credit_txn') THEN EXECUTE 'CREATE POLICY "staff_finance_read_store_credit_txn" ON public.store_credit_transactions AS PERMISSIVE FOR SELECT TO PUBLIC USING ((has_role(auth.uid(), ''staff''::app_role) OR has_role(auth.uid(), ''finance''::app_role)))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='website_categories' AND policyname='Staff can manage website categories') THEN EXECUTE 'CREATE POLICY "Staff can manage website categories" ON public.website_categories AS PERMISSIVE FOR ALL TO "authenticated" USING (is_staff(auth.uid())) WITH CHECK (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='website_categories' AND policyname='Staff can view website categories') THEN EXECUTE 'CREATE POLICY "Staff can view website categories" ON public.website_categories AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='website_category_products' AND policyname='Staff can manage category products') THEN EXECUTE 'CREATE POLICY "Staff can manage category products" ON public.website_category_products AS PERMISSIVE FOR ALL TO "authenticated" USING (is_staff(auth.uid())) WITH CHECK (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='website_category_products' AND policyname='Staff can view category products') THEN EXECUTE 'CREATE POLICY "Staff can view category products" ON public.website_category_products AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='website_testimonials' AND policyname='Staff can manage website testimonials') THEN EXECUTE 'CREATE POLICY "Staff can manage website testimonials" ON public.website_testimonials AS PERMISSIVE FOR ALL TO "authenticated" USING (is_staff(auth.uid())) WITH CHECK (is_staff(auth.uid()))'; END IF; END $p$;
DO $p$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='website_testimonials' AND policyname='Staff can view website testimonials') THEN EXECUTE 'CREATE POLICY "Staff can view website testimonials" ON public.website_testimonials AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_staff(auth.uid()))'; END IF; END $p$;
ALTER TABLE public.cash_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pancake_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shopify_webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_credit_lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_credit_reconciliation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_credit_shopify_sync ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_category_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_faq_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_faq_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_testimonials ENABLE ROW LEVEL SECURITY;
